# Generated by Django 2.1 on 2018-09-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('priceNew', models.FloatField()),
                ('engineSize', models.FloatField()),
                ('fuelSystem', models.CharField(max_length=50)),
                ('tankCapacity', models.FloatField()),
                ('power', models.FloatField()),
                ('seatingCapacity', models.FloatField()),
                ('standardTransmission', models.CharField(max_length=50)),
                ('bodyType', models.CharField(max_length=50)),
                ('drive', models.CharField(max_length=5)),
                ('wheelBase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('createDate', models.DateField()),
                ('pickupDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickupStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pickup_store', to='RentalApp.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='returnStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_store', to='RentalApp.Store'),
        ),
    ]
