# Generated by Django 2.1 on 2018-10-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnDate', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Car')),
                ('returnStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_return_store', to='RentalApp.Store')),
            ],
        ),
    ]
