# Generated by Django 2.1 on 2018-10-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickupStore',
        ),
        migrations.RemoveField(
            model_name='order',
            name='returnStore',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
