# Generated by Django 2.1 on 2018-09-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('priceNew', models.FloatField()),
                ('engineSize', models.FloatField()),
                ('fuelSystem', models.CharField(max_length=50)),
                ('tankCapacity', models.FloatField()),
                ('power', models.FloatField()),
                ('seatingCapacity', models.FloatField()),
                ('standardTransmission', models.CharField(max_length=50)),
                ('bodyType', models.CharField(max_length=50)),
                ('drive', models.CharField(max_length=5)),
                ('wheelBase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelTest',
        ),
    ]
