# Generated by Django 2.1 on 2018-10-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0002_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stocks',
        ),
    ]
