# Generated by Django 2.1 on 2018-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0002_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seatingCapacity',
            field=models.IntegerField(),
        ),
    ]
