# Generated by Django 2.1 on 2018-09-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0002_auto_20180903_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='createDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickupDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickupStore',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_pickup_store', to='RentalApp.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='returnDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='returnStore',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='return_store', to='RentalApp.Store'),
            preserve_default=False,
        ),
    ]
