# Generated by Django 2.1 on 2018-10-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0003_auto_20181018_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
