# Generated by Django 2.1 on 2018-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0003_auto_20180905_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
