# Generated by Django 2.1 on 2018-10-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0003_auto_20181017_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidanStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnDate', models.DateField()),
                ('returnStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aidan_stock_return_store', to='RentalApp.Store')),
            ],
        ),
    ]
