# Generated by Django 2.1 on 2018-10-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0004_auto_20181008_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('createDate', models.DateField()),
                ('pickupDate', models.DateField()),
                ('pickupStore', models.IntegerField()),
                ('returnDate', models.DateField()),
                ('returnStore', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Customer')),
            ],
        ),
    ]
