# Generated by Django 2.1 on 2018-09-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0004_auto_20180905_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickupStore',
        ),
        migrations.RemoveField(
            model_name='order',
            name='returnStore',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
