# Generated by Django 2.1 on 2018-10-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0004_aidanstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidanstock',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aidan_stock_car', to='RentalApp.Car'),
            preserve_default=False,
        ),
    ]
