# Generated by Django 2.1 on 2018-09-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0005_auto_20180905_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
