# Generated by Django 2.1 on 2018-10-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0004_auto_20181019_0034'),
        ('RentalApp', '0005_aidanstock_car'),
    ]

    operations = [
    ]
