# Generated by Django 2.1 on 2018-09-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0007_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('createDate', models.DateField()),
                ('pickupDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.Customer')),
                ('pickupStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pickup_store', to='RentalApp.Store')),
                ('returnStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_store', to='RentalApp.Store')),
            ],
        ),
    ]
